"""Add location and tag columns to DocumentIndexTable

Revision ID: 7cd59fa30b10
Revises: 
Create Date: 2024-06-14 10:28:46.425469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd59fa30b10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_index', sa.Column('location', sa.Integer(), nullable=False))
    op.add_column('document_index', sa.Column('tag', sa.String(length=50), nullable=True))
    # op.alter_column('ips', 'domain',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False)
    # op.alter_column('ips', 'ip',
    #            existing_type=sa.VARCHAR(length=15),
    #            nullable=True)
    # op.drop_column('url_frontier', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('url_frontier', sa.Column('score', sa.FLOAT(), nullable=True))
    # op.alter_column('ips', 'ip',
    #            existing_type=sa.VARCHAR(length=15),
    #            nullable=False)
    # op.alter_column('ips', 'domain',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True)
    op.drop_column('document_index', 'tag')
    op.drop_column('document_index', 'location')
    # ### end Alembic commands ###
